"""
Stage 3: train the policy model via behavior cloning on the policy dataset
generated by a frozen selector.

The backend is dispatched on config `pipeline.policy_dataset`:
  - "h5": flat (buffer, action) pairs in HDF5 (synthetic and grid domains).
  - "lerobot": LeRobot video dataset with dict observations (robot domains).

Usage:
    python -m keyframe_mnemonics.train_policy --experiment_name tmaze --selector_checkpoint tmaze_<TAG>
"""
import argparse
import os
import glob
import yaml
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from pathlib import Path
from datetime import datetime
import wandb

from models import model_dict
from problems import problem_dict
from keyframe_mnemonics.memory_manager import MemoryManager
from common.helpers import set_seeds, parse_experiment_name, get_problem_type_and_conf_path, stage_dir, tee_stdout


class PolicyDataset(Dataset):
    """Stage-3 dataset wrapping a MemoryManager of (buffer, action) pairs
    produced by rolling out a frozen selector (in-memory or H5-backed)."""

    def __init__(self, memory, action_dim):
        self.action_dim = action_dim
        self.memory = memory

    def __len__(self):
        return len(self.memory)

    def __getitem__(self, idx):
        return self.memory.read(idx)

    def get_sample_weights(self):
        actions = self.memory.outputs_array()[:, 0].astype(int)
        counts = np.bincount(actions, minlength=self.action_dim)
        return torch.from_numpy(1.0 / counts[actions].clip(min=1)).float()

    def close(self):
        self.memory.close()


def _resolve_run_folder(experiment_name, selector_checkpoint, resume_checkpoint):
    """The policy stage writes into the same run folder as its upstream selector.

    Falls back to the resume checkpoint's run folder, or mints a fresh run folder
    when the policy stage is run in isolation.
    """
    if selector_checkpoint:
        return selector_checkpoint
    if resume_checkpoint:
        return resume_checkpoint
    tag = datetime.now().strftime("%Y%m%d_%H%M%S")
    return f"{experiment_name}_{tag}"


def _create_policy_checkpoint_dir(run_folder, path_prefix, config):
    """Create the policy stage subfolder inside the run folder and save the config."""
    checkpoint_path = Path(stage_dir(path_prefix, run_folder, "policy"))
    checkpoint_path.mkdir(parents=True, exist_ok=True)
    tee_stdout(checkpoint_path / "train.log")
    with open(checkpoint_path / "config.yaml", 'w') as f:
        yaml.dump(config, f, default_flow_style=False)
    print(f"Checkpoint directory: {checkpoint_path}")
    return checkpoint_path


# ---------------------------------------------------------------------------
# Flat-H5 backend (synthetic and grid domains)
# ---------------------------------------------------------------------------

def _train_flat_policy(experiment_name, problem_type, config, selector_checkpoint, seed, device):
    path_prefix = config.get("path_prefix", "")
    policy_config = config["policy"]
    model_config = policy_config["model_kwargs"]
    problem_config = dict(config["problem"])
    problem_config.update(config.get("policy_problem_override", {}))
    action_dim = problem_config["action_dim"]

    # Policy stage subfolder inside the run folder (shared with the selector stage)
    run_folder = _resolve_run_folder(experiment_name, selector_checkpoint, "")

    # Acquire the dataset by rolling out the frozen selector. cache_path "" keeps it
    # in RAM; anything else writes/streams an H5 into the run folder.
    cache_path = policy_config.get("cache_path", "")
    generate = problem_dict.get(problem_type).get("policy_dataset_generator")
    if cache_path:
        cache_path = stage_dir(path_prefix, run_folder, "policy_dataset")
        h5_path = os.path.join(cache_path, f"{experiment_name}_policy_dataset.h5")
        if os.path.exists(h5_path):
            print(f"Using existing policy dataset: {h5_path}")
            memory = MemoryManager.open(h5_path)
        else:
            memory = generate(selector_checkpoint, cache_path=cache_path, seed=seed)
    else:
        print("Generating policy dataset in memory")
        memory = generate(selector_checkpoint, cache_path="", seed=seed)
    dataset = PolicyDataset(memory, action_dim=action_dim)
    print(f"Dataset size: {len(dataset)}")

    balance_sampler = policy_config.get("balance_sampler", False)
    sample_weights = dataset.get_sample_weights() if balance_sampler else None

    if balance_sampler:
        sampler = WeightedRandomSampler(sample_weights, num_samples=len(dataset), replacement=True)
        print("Weighted sampler enabled")

    # In-RAM data -> load in the main process; streaming from H5 -> persistent
    # workers to hide read latency.
    stream = memory.use_h5
    dataloader = DataLoader(
        dataset,
        batch_size=policy_config.get("batch_size", 256),
        sampler=sampler if balance_sampler else None,
        shuffle=not balance_sampler,
        num_workers=4 if stream else 0,
        persistent_workers=stream,
    )

    # Model
    policy_class = model_dict.get(problem_type).get("policy")
    if policy_class is None:
        raise ValueError(f"No policy model found for problem_type: {problem_type}")
    model = policy_class(output_dim=action_dim, device=device, **model_config).to(device)
    print(f"Policy parameters: {sum(p.numel() for p in model.parameters()):,}")

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=policy_config.get("learning_rate", 1e-3),
        weight_decay=policy_config.get("weight_decay", 0.0),
    )

    checkpoint_path = _create_policy_checkpoint_dir(run_folder, path_prefix, config)

    # Optional policy validation + early stopping (mirrors the lerobot backend).
    if config.get("logging", False):
        wandb.init(project="keyframe_mnemonics", name=f"{run_folder}_policy", group=run_folder, job_type="policy", config=config, tags=[experiment_name])

    policy_evaluator = None
    eval_fn = None
    evaluator_config = config.get("policy_evaluator")
    if evaluator_config is not None:
        if not selector_checkpoint:
            raise ValueError("selector_checkpoint is required when policy_evaluator config is present")
        from rollout import eval_dict
        eval_fn_getter = eval_dict.get(problem_type)
        policy_evaluator_class = problem_dict.get(problem_type).get("policy_evaluator")
        if not eval_fn_getter or not policy_evaluator_class:
            raise ValueError(f"No eval_fn or policy_evaluator registered for problem_type: {problem_type}")
        eval_fn = eval_fn_getter()
        policy_evaluator = policy_evaluator_class(**evaluator_config)
        print("Policy evaluator initialized.")

    training_steps = policy_config.get("training_steps", 5000)
    save_interval = policy_config.get("save_interval", 1000)

    model.train()
    dataloader_iter = iter(dataloader)
    losses = []
    log_interval = max(1, training_steps // 20)
    for step in range(training_steps):
        try:
            buf, tgt = next(dataloader_iter)
        except StopIteration:
            dataloader_iter = iter(dataloader)
            buf, tgt = next(dataloader_iter)

        buf, tgt = buf.to(device), tgt.to(device)
        optimizer.zero_grad()
        loss = model.compute_loss(buf, tgt)
        loss.backward()
        optimizer.step()
        losses.append(loss.item())

        if (step + 1) % log_interval == 0:
            print(f"Step {step + 1}/{training_steps} | loss: {sum(losses) / len(losses):.4f}")
            losses.clear()

        if (step + 1) % save_interval == 0:
            ckpt = checkpoint_path / f"{experiment_name}_policy_{step + 1}.pth"
            torch.save(
                {"model_state_dict": model.state_dict(), "optimizer_state_dict": optimizer.state_dict()},
                ckpt,
            )
            print(f"Saved: {ckpt}")

            if policy_evaluator is not None:
                model.eval()
                converged = policy_evaluator.evaluate(eval_fn, run_folder, step + 1)
                model.train()
                if converged:
                    print(f"Early stopping at step {step + 1}: validation threshold achieved.")
                    break

    if training_steps % save_interval != 0:
        final = checkpoint_path / f"{experiment_name}_policy_{training_steps}.pth"
        torch.save(
            {"model_state_dict": model.state_dict(), "optimizer_state_dict": optimizer.state_dict()},
            final,
        )
        print(f"Final model saved: {final}")

    dataset.close()
    if wandb.run is not None:
        wandb.finish()
    print("Policy training complete.")
    return run_folder


# ---------------------------------------------------------------------------
# LeRobot backend (robot domains)
# ---------------------------------------------------------------------------

def _save_lerobot_checkpoint(model, optimizer, path):
    ckpt = {'model_state_dict': model.state_dict(), 'optimizer_state_dict': optimizer.state_dict()}
    torch.save(ckpt, path)


def _train_lerobot_policy(experiment_name, problem_type, config, selector_checkpoint,
                          resume_checkpoint, seed, device):
    # LeRobot-stack imports are local so the flat backend works without them installed
    import json
    from lerobot.datasets.lerobot_dataset import LeRobotDataset
    from common.augmentation import ImageAugmenter
    from rollout import eval_dict

    # Reload config from the resume checkpoint if provided
    if resume_checkpoint:
        path_prefix = config.get("path_prefix", "")
        resume_path = stage_dir(path_prefix, resume_checkpoint, "policy")
        conf_path = os.path.join(resume_path, "config.yaml")
        with open(conf_path) as cf:
            config = yaml.safe_load(cf)
        print(f"Reloaded config: {conf_path}")

    policy_config = config.get("policy")
    model_config = policy_config.get("model_kwargs")
    path_prefix = config.get("path_prefix", "")

    # Policy stage subfolder inside the run folder (shared with the selector stage)
    run_folder = _resolve_run_folder(experiment_name, selector_checkpoint, resume_checkpoint)
    checkpoint_folder = run_folder

    # The dataset belongs to this run, so it lives beside the stage checkpoints
    repo_id = f"{experiment_name}_policy_dataset"
    lerobot_dataset_path = stage_dir(path_prefix, run_folder, "policy_dataset")

    # Materialize the dataset by rolling out the frozen selector if it isn't on
    # disk yet (checking meta/info.json avoids reusing a half-written dataset).
    if not os.path.exists(os.path.join(lerobot_dataset_path, "meta/info.json")):
        generate = problem_dict.get(problem_type).get("policy_dataset_generator")
        if generate is None:
            raise ValueError(f"No policy_dataset_generator registered for problem_type: {problem_type}")
        print(f"Policy dataset not found; generating at {lerobot_dataset_path}")
        generate(selector_checkpoint, output_dir=lerobot_dataset_path, seed=seed)

    checkpoint_path = _create_policy_checkpoint_dir(run_folder, path_prefix, config)

    # Initialize wandb if logging is enabled
    if config.get("logging", False):
        wandb.init(
            project="keyframe_mnemonics",
            name=f"{run_folder}_policy",
            group=run_folder,
            job_type="policy",
            config=config,
            tags=[experiment_name]
        )

    # Load LeRobot dataset with action horizon from config
    horizon = model_config.get("horizon", 8)
    print(f"Loading LeRobot dataset from: {lerobot_dataset_path}")
    print(f"Action horizon: {horizon}")

    # Read fps from dataset metadata
    info_path = os.path.join(lerobot_dataset_path, "meta/info.json")
    with open(info_path, 'r') as f:
        info = json.load(f)
    fps = info['fps']
    delta_timestamps = {"action": [t / fps for t in range(horizon)]}

    # Load dataset with delta_timestamps
    dataset = LeRobotDataset(repo_id, root=lerobot_dataset_path, delta_timestamps=delta_timestamps)
    print(f"Total episodes: {dataset.meta.total_episodes}")
    print(f"Total frames: {dataset.meta.total_frames}")

    # Setup policy evaluator if evaluator config is present
    evaluator_config = config.get("policy_evaluator")
    policy_evaluator = None
    eval_fn = None
    if evaluator_config is not None:
        if not selector_checkpoint:
            raise ValueError("selector_checkpoint is required when policy_evaluator config is present")
        eval_fn_getter = eval_dict.get(problem_type)
        policy_evaluator_class = problem_dict.get(problem_type).get("policy_evaluator")
        if not eval_fn_getter or not policy_evaluator_class:
            raise ValueError(f"No eval_fn or policy_evaluator registered for problem_type: {problem_type}")
        eval_fn = eval_fn_getter()
        policy_evaluator = policy_evaluator_class(**evaluator_config)
        print("Policy evaluator initialized.")

    # Create dataloader
    batch_size = policy_config.get("batch_size", 256)
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=8
    )

    # Get action dimension from dataset metadata
    action_dim = dataset.meta.features['action']['shape'][0]
    print(f"Action dim: {action_dim}")

    # Get policy model class from model dict
    policy_class = model_dict.get(problem_type).get("policy")
    if policy_class is None:
        raise ValueError(f"No policy model found for problem_type: {problem_type}")

    # Create model
    print("Initializing policy model...")
    model = policy_class(
        output_dim=action_dim,
        **model_config
    ).to(device)

    print(f"Policy parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")

    # Optimizer
    lr = policy_config.get("learning_rate", 1e-4)
    weight_decay = policy_config.get("weight_decay", 0.0)
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)

    # Resume from checkpoint if provided
    if resume_checkpoint:
        # Extract experiment_name from the run folder
        resume_experiment_name = parse_experiment_name(resume_checkpoint)

        # Find the last checkpoint automatically
        pattern = os.path.join(resume_path, f"{resume_experiment_name}_policy_*.pth")
        checkpoints = glob.glob(pattern)
        if not checkpoints:
            raise FileNotFoundError(f"No checkpoints found matching {pattern}")
        checkpoint_file = max(checkpoints, key=lambda x: int(x.split('_')[-1].split('.')[0]))

        checkpoint = torch.load(checkpoint_file, map_location=device, weights_only=False)
        model.load_state_dict(checkpoint['model_state_dict'])
        optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
        print(f"Loaded policy model and optimizer from {checkpoint_file}")

    # Training loop
    model.train()
    print("Starting training...")

    training_steps = policy_config.get("training_steps", 5000)
    save_interval = policy_config.get("save_interval", 1000)
    augmenter = ImageAugmenter()

    # Create infinite dataloader iterator
    dataloader_iterator = iter(dataloader)

    log_interval = max(1, training_steps // 20)
    losses = []
    for step in range(training_steps):
        # Get next batch (restart iterator if exhausted)
        try:
            batch = next(dataloader_iterator)
        except StopIteration:
            dataloader_iterator = iter(dataloader)
            batch = next(dataloader_iterator)

        # Move batch to device
        observations = {k: v.to(device) if isinstance(v, torch.Tensor) else v
                        for k, v in batch.items() if k.startswith('observation')}
        expert_actions = batch['action'].to(device)

        observations = augmenter(observations)

        optimizer.zero_grad()
        loss = model.compute_loss(observations, expert_actions)
        loss.backward()
        optimizer.step()
        losses.append(loss.item())

        if (step + 1) % log_interval == 0:
            print(f"Step {step + 1}/{training_steps} | loss: {sum(losses) / len(losses):.4f}")
            losses.clear()

        # Log to wandb
        if wandb.run is not None:
            wandb.log({
                'step': step + 1,
                'policy_loss': loss.item()
            })

        # Save checkpoint
        if (step + 1) % save_interval == 0:
            checkpoint_file = checkpoint_path / f"{experiment_name}_policy_{step+1}.pth"
            _save_lerobot_checkpoint(model, optimizer, checkpoint_file)
            print(f"Saved checkpoint: {checkpoint_file}")

            # Run evaluation if configured
            if policy_evaluator is not None:
                model.eval()
                converged = policy_evaluator.evaluate(eval_fn, checkpoint_folder, step + 1)
                model.train()
                if converged:
                    print(f"Early stopping at step {step+1}: success rate threshold achieved!")
                    break

    # Save final model only if not already saved at last interval
    if training_steps % save_interval != 0:
        final_file = checkpoint_path / f"{experiment_name}_policy_{training_steps}.pth"
        _save_lerobot_checkpoint(model, optimizer, final_file)
        print(f"Training completed. Final model saved: {final_file}")
    else:
        print("Training completed.")

    if wandb.run is not None:
        wandb.finish()

    return checkpoint_folder


# ---------------------------------------------------------------------------

def train(experiment_name, seed=None, selector_checkpoint="", resume_checkpoint=""):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    if seed is not None:
        set_seeds(seed=seed)

    # Load config
    problem_type, conf_path = get_problem_type_and_conf_path(experiment_name)
    with open(conf_path) as f:
        config = yaml.safe_load(f)
    print(f"Loading config: {conf_path}")

    backend = config.get("pipeline").get("policy_dataset")
    if backend == "lerobot":
        return _train_lerobot_policy(experiment_name, problem_type, config,
                                     selector_checkpoint, resume_checkpoint, seed, device)
    elif backend == "h5":
        if resume_checkpoint:
            raise ValueError("resume_checkpoint is not supported by the flat-H5 policy backend")
        return _train_flat_policy(experiment_name, problem_type, config,
                                  selector_checkpoint, seed, device)
    raise ValueError(f"Unknown pipeline.policy_dataset backend: {backend}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train Policy Model using Behavioral Cloning")

    parser.add_argument("--experiment_name", type=str, default="tmaze",
                        help="Experiment name (yaml config filename, encodes problem type as prefix)")
    parser.add_argument("--seed", type=int, default=None,
                        help="Random seed")
    parser.add_argument("--selector_checkpoint", type=str, default="",
                        help="Selector checkpoint directory name to copy into policy checkpoint")
    parser.add_argument("--resume_checkpoint", type=str, default="",
                        help="Resume training from checkpoint directory (lerobot backend only)")

    args = parser.parse_args()
    train(args.experiment_name, seed=args.seed,
          selector_checkpoint=args.selector_checkpoint,
          resume_checkpoint=args.resume_checkpoint)
