logging: &logging False
path_prefix: &path_prefix ""

pipeline:
  proxy_dataset: rollout
  policy_dataset: h5

problem:
  env_list:
    - "MiniGrid-MemoryS17Random-v0"
  split: "train"
  action_dim: 7
  buffer_size: &buffer_size 2
  num_variations: 2000
  randomize_reset: True
  horizon: &horizon 1
  path_prefix: *path_prefix

test_problem_override:
  num_variations: 100
  split: "test"
  env_options:
    size: 1001

policy_problem_override:
  buffer_size: 1
  num_variations: 4500

selector_env:
  n_envs: 32
  action_penalty: 0.0
  min_loss: 0.01
  reward_scaling_tau: 0.2

selector:
  total_timesteps: 300000
  n_steps: 512
  batch_size: 128
  n_epochs: 5
  learning_rate: 0.0003
  logging: *logging
  features_extractor_kwargs:
    hidden_dim: 128
    features_dim: 64

proxy:
  batch_size: 512
  learning_rate: 0.001
  rollout_multiplier: 300
  training_epochs: 10
  save_interval: 10
  cache_path: "datasets/ltmb/proxy_cache"
  model_kwargs:
    total_slots: *buffer_size
    hidden_dim: 128
    attn_heads: 4
    entropy_coef: 0.01
    horizon: *horizon

policy:
  batch_size: 256
  learning_rate: 0.0001
  weight_decay: 0.0
  training_steps: 100000
  save_interval: 10000
  balance_sampler: True
  cache_path: ""
  model_kwargs:
    total_slots: 2
    hidden_dim: 64
    attn_heads: 4
    entropy_coef: 0.01
    horizon: 1

evaluator:
  sr_threshold: 0.70
  rw_threshold: 0.40
  logging: *logging
  evaluation_rollouts: 10
  path_prefix: *path_prefix

policy_evaluator:
  sr_threshold: 0.99
  logging: *logging
  evaluation_rollouts: 50
