path_prefix: &path_prefix ""

pipeline:
  proxy_dataset: rollout
  policy_dataset: h5

problem:
  maze_type: "active"  # "active" or "passive"
  min_corridor_length: 2
  max_corridor_length: 5
  action_dim: 2
  buffer_size: &buffer_size 2
  num_variations: 100
  randomize_reset: True

test_problem_override:
  min_corridor_length: 100
  max_corridor_length: 1000
  num_variations: 100

selector_env:
  n_envs: 16
  action_penalty: 0.0
  min_loss: 0.000001

selector:
  total_timesteps: 200000
  n_steps: 512
  batch_size: 64
  n_epochs: 10
  learning_rate: 0.0003
  features_extractor_kwargs:
    features_dim: 16

proxy:
  batch_size: 256
  learning_rate: 0.001
  rollout_multiplier: 300
  training_epochs: 10
  save_interval: 10
  cache_path: ""
  model_kwargs:
    total_slots: *buffer_size
    embd_dim: 256

policy:
  batch_size: 256
  learning_rate: 0.001
  weight_decay: 0.0
  training_steps: 5000  # matches proxy gradient budget: proxy epochs x (num_variations * rollout_multiplier * seq_len / batch_size)
  save_interval: 5000
  balance_sampler: False
  cache_path: ""
  model_kwargs:
    total_slots: 3 # buffer_size + current obs
    embd_dim: 256

evaluator:
  loss_threshold: 0.0001
  evaluation_rollouts: 10
  path_prefix: *path_prefix

policy_evaluator:
  sr_threshold: 0.99
  logging: False
  evaluation_rollouts: 10
